// Destructive ONLY in an isolated local *_test DB; never connect this suite to Supabase.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {randomUUID,createHash} from 'node:crypto';
const require=createRequire(new URL('../api/package.json',import.meta.url));
const root=new URL('../',import.meta.url).pathname;
const url=new URL(process.env.DATABASE_URL||'postgresql://invalid/invalid');
if(!['127.0.0.1','localhost','postgres'].includes(url.hostname)||!url.pathname.endsWith('_test')||process.env.NODE_ENV==='production')throw Error('Only isolated local *_test databases allowed');
process.env.PGSSL='false';process.env.JWT_SECRET||='integration-only-session-secret-at-least-32';process.env.PIN_PEPPER||='integration-only-pin-pepper-at-least-32';process.env.MFA_ENCRYPTION_KEY||='ab'.repeat(32);
const {pool,one,query}=require('../api/dist/db'),{signToken}=require('../api/dist/auth');const bcrypt=require('bcryptjs');
let child,logs='',failStorage=false,count=0;const deleted=[];
const ok=(v,m)=>{assert(v,m);console.log('PASS',m);count++;};
const storage=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;res.setHeader('Content-Type','application/json');if(req.method==='DELETE'&&req.url.startsWith('/storage/v1/object/')){if(failStorage){res.statusCode=503;return res.end('{}');}deleted.push({url:req.url,keys:JSON.parse(body).prefixes});return res.end('[]');}res.statusCode=404;res.end('{}');});
const base='http://127.0.0.1:4020/api';
async function call(p,method='GET',body,token){const r=await fetch(base+p,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),headers:r.headers};}
const completion={confirmation:'COMPLETE REVIEWED DELETION',history_reviewed:true,external_copies_reviewed:true,financial_reviewed:true,retention_summary:'Test-only retained transaction and minimal closure records; synthetic retention decision. No real personal information.',retention_review_date:'2099-01-01',public_message:'Test profile and known files removed; historical synthetic records retained as documented.'};
try{
 await query('delete from security_rate_limits');await new Promise(r=>storage.listen(0,'127.0.0.1',r));
 const storageUrl='http://127.0.0.1:'+storage.address().port;
 child=spawn(process.execPath,['dist/server.js'],{cwd:root+'api',env:{...process.env,PORT:'4020',EMAIL_PROVIDER:'none',SUPABASE_URL:storageUrl,SUPABASE_SERVICE_ROLE_KEY:'local-stub-only',SUPABASE_PRIVATE_BUCKET:'vendor-documents',SUPABASE_BUCKET:'listings'},stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error(logs)),10000);child.stdout.on('data',d=>{logs+=d;if(logs.includes('listening on')){clearTimeout(t);resolve();}});child.stderr.on('data',d=>logs+=d);child.once('exit',()=>{clearTimeout(t);reject(Error(logs));});});
 const password='Deletion-test-password!',hash=await bcrypt.hash(password,10);
 async function user(role='buyer'){return one("insert into users(full_name,phone,email,password_hash,role) values('Deletion Test',$1,$2,$3,$4) returning *",[randomUUID(),randomUUID()+'@example.invalid',hash,role]);}
 const a=await user('admin'),b=await user(),other=await user(),vu=await user('vendor');
 const at=await signToken(a.id,'admin'),bt=await signToken(b.id,'buyer'),ot=await signToken(other.id,'buyer'),vt=await signToken(vu.id,'vendor');
 const body={password,acknowledge:true,reason:'TEST REASON PRIVATE'};
 ok((await call('/account-deletion/requests','POST',body)).status===401,'anonymous request rejected');
 ok((await call('/account-deletion/admin','GET',undefined,bt)).status===403,'buyer cannot read admin queue');
 ok((await call('/account-deletion/requests','POST',body,at)).status===403,'administrators cannot self-delete');
 ok((await call('/account-deletion/requests','POST',{...body,password:'wrong'},bt)).status===400,'current password required');
 ok((await call('/account-deletion/requests','POST',{...body,acknowledge:false},bt)).status===400,'explicit request acknowledgement required');
 const imp=await call('/admin/users/'+b.id+'/impersonate','POST',{},at);
 ok((await call('/account-deletion/requests','POST',body,imp.data.token)).status===403,'impersonation cannot request deletion');
 const race=await Promise.all([call('/account-deletion/requests','POST',body,bt),call('/account-deletion/requests','POST',body,bt)]);
 ok(race.filter(r=>r.status===201).length===1&&race.filter(r=>r.status===409).length===1,'concurrent duplicate requests serialize to one open request');
 const receipt=race.find(r=>r.status===201).data,request=receipt.request;
 const db=await one('select * from account_deletion_requests where id=$1',[request.id]);
 ok(db.access_hash===createHash('sha256').update(receipt.access_token).digest('hex')&&db.access_hash!==receipt.access_token,'receipt key is stored hashed, never plaintext');
 ok((await call('/account-deletion/requests/'+request.id+'/withdraw','POST',{},ot)).status===409,'other customer cannot withdraw request');
 const unrelated=await call('/account-deletion/requests','GET',undefined,ot);ok(unrelated.data.requests.length===0,'customers only see their own requests');
 ok((await call('/account-deletion/status','POST',{reference:request.reference,access_token:'0'.repeat(64)})).status===404,'incorrect receipt key rejected');
 const review=await call('/account-deletion/admin/'+request.id,'PATCH',{status:'needs_action',public_message:'Please resolve the outstanding matter.',internal_note:'INTERNAL SECRET'},at);ok(review.status===200,'admin review update works');
 const track=await call('/account-deletion/status','POST',{reference:request.reference,access_token:receipt.access_token});
 ok(track.status===200&&track.data.request.status==='needs_action','receipt tracks status without login');
 ok(!JSON.stringify(track.data).includes('INTERNAL SECRET')&&!JSON.stringify(track.data).includes('TEST REASON PRIVATE')&&!('user_id' in track.data.request),'public receipt excludes identity, reason and internal notes');
 ok(track.headers.get('cache-control')==='no-store','privacy responses are not cacheable');
 ok(!(JSON.stringify((await call('/account-deletion/admin','GET',undefined,at)).data).includes(db.access_hash)),'admin queue does not expose hashed receipt keys');
 ok((await call('/account-deletion/requests/'+request.id+'/withdraw','POST',{},bt)).status===200,'requester can withdraw before processing');
 ok((await call('/account-deletion/admin/'+request.id+'/complete','POST',completion,at)).status===409,'withdrawn request cannot be completed');
 await query('delete from security_rate_limits');
 const r2=(await call('/account-deletion/requests','POST',body,bt)).data;
 ok((await call('/account-deletion/admin/'+r2.request.id+'/complete','POST',{...completion,history_reviewed:false},at)).status===400,'completion requires explicit historical-data review');
 ok((await call('/account-deletion/admin/'+r2.request.id+'/complete','POST',{...completion,retention_review_date:'2099-02-31'},at)).status===400,'invalid calendar dates rejected');
 ok((await call('/account-deletion/admin/'+r2.request.id+'/complete','POST',{...completion,retention_review_date:'2000-01-01'},at)).status===400,'past retention review dates rejected');
 const v=await one("insert into vendors(user_id,business_name,slug,whatsapp,country,city,status) values($1,'Deletion Store',$2,'97455551111','Qatar','Doha','verified') returning *",[vu.id,'del-'+randomUUID()]);
 const cat=await one("insert into categories(name,slug,kind) values($1,$2,'product') returning *",['Deletion '+randomUUID(),'del-'+randomUUID()]);
 const item=await one("insert into listings(vendor_id,category_id,kind,title,slug,price,quantity,status) values($1,$2,'product','Deletion item','deletion-item',50,10,'active') returning *",[v.id,cat.id]);
 async function order(buyer,status='pending'){return one("insert into orders(code,vendor_id,buyer_id,status,contact_name,contact_phone,delivery_address,city,country) values($1,$2,$3,$4,'Historical Contact','97455550002','Historical address','Doha','Qatar') returning *",['DEL-ORDER-'+randomUUID(),v.id,buyer,status]);}
 const o=await order(b.id);
 ok((await call('/account-deletion/admin/'+r2.request.id+'/complete','POST',completion,at)).status===409,'open customer order blocks completion');
 ok((await one('select is_active from users where id=$1',[b.id])).is_active,'blocked completion does not disable account');
 await query("update orders set status='delivered' where id=$1",[o.id]);
 const booking=await one("insert into service_bookings(code,listing_id,vendor_id,buyer_id,contact_name,contact_phone,status) values($1,$2,$3,$4,'Historical buyer','97455550002','confirmed') returning *",['DEL-BOOK-'+randomUUID(),item.id,v.id,b.id]);
 ok((await call('/account-deletion/admin/'+r2.request.id+'/complete','POST',completion,at)).status===409,'open service booking blocks completion');
 await query("update service_bookings set status='completed' where id=$1",[booking.id]);
 const complaint=await one("insert into complaints(code,reporter_id,subject,body) values($1,$2,'Synthetic complaint','Synthetic body') returning *",['DEL-COMP-'+randomUUID(),b.id]);
 ok((await call('/account-deletion/admin/'+r2.request.id+'/complete','POST',completion,at)).status===409,'unresolved complaint blocks completion');
 await query("update complaints set status='resolved' where id=$1",[complaint.id]);
 await query("update account_deletion_requests set processing_claim=$2,processing_claim_until=now()+interval '10 minutes' where id=$1",[r2.request.id,randomUUID()]);
 ok((await call('/account-deletion/admin/'+r2.request.id+'/complete','POST',completion,at)).status===409,'concurrent completion lease prevents conflicting administrator decisions');
 await query("update account_deletion_requests set processing_claim_until=now()-interval '1 second' where id=$1",[r2.request.id]);
 const completed=await call('/account-deletion/admin/'+r2.request.id+'/complete','POST',completion,at);
 assert.equal(completed.status,200,JSON.stringify(completed.data));ok(completed.data.request.status==='completed','reviewed buyer completion works, including expired interrupted lease recovery');
 const bu=await one('select * from users where id=$1',[b.id]);
 ok(!bu.is_active&&bu.deleted_at&&bu.full_name==='Deleted account'&&!bu.email&&bu.phone==='deleted-'+b.id&&!await bcrypt.compare(password,bu.password_hash)&&!bu.pin_hash,'profile and credentials anonymised, not merely disabled');
 ok((await call('/auth/me','GET',undefined,bt)).status===401&&(await one('select count(*)::int n from auth_sessions where user_id=$1',[b.id])).n===0,'all target sessions removed');
 ok((await one('select * from orders where id=$1',[o.id])).contact_name==='Historical Contact','transaction history preserved for explicit manual retention review');
 ok((await one('select * from service_bookings where id=$1',[booking.id])).id===booking.id,'booking history not cascade-deleted');
 ok((await call('/account-deletion/status','POST',{reference:r2.request.reference,access_token:r2.access_token})).data.request.status==='completed','receipt remains usable after account closure');
 ok((await call('/admin/users/'+b.id,'PATCH',{is_active:true},at)).status===404,'ordinary admin enable cannot resurrect deleted profile');
 await assert.rejects(()=>query('update users set is_active=true where id=$1',[b.id]));ok(true,'database also rejects profile resurrection');
 await assert.rejects(()=>order(b.id));ok(true,'in-flight checkout cannot create order for closed buyer');
 const vr=(await call('/account-deletion/requests','POST',body,vt)).data;
 const statement=await one("insert into vendor_statements(vendor_id,period_start,period_end,status,net_due_to_platform) values($1,'2090-01-01','2090-01-31','issued',10) returning *",[v.id]);
 ok((await call('/account-deletion/admin/'+vr.request.id+'/complete','POST',completion,at)).status===409,'unsettled vendor statement blocks completion');
 await query("update vendor_statements set status='paid' where id=$1",[statement.id]);
 const preserved=await order(other.id,'delivered');
 const key=vu.id+'/cr.jpg',otherKey=other.id+'/other.jpg';await query('insert into private_uploads(key,user_id,bytes) values($1,$2,100),($3,$4,100)',[key,vu.id,otherKey,other.id]);
 await query('update vendors set id_document_url=$2,logo_url=$3,bank_iban=$4 where id=$1',[v.id,'kyc://'+key,storageUrl+'/storage/v1/object/public/listings/'+vu.id+'/logo.jpg','QA-TEST-IBAN']);
 await query('update listings set images=$2 where id=$1',[item.id,JSON.stringify([storageUrl+'/storage/v1/object/public/listings/'+vu.id+'/item.jpg'])]);
 failStorage=true;const failure=await call('/account-deletion/admin/'+vr.request.id+'/complete','POST',completion,at);
 ok(failure.status===503&&(await one('select status from account_deletion_requests where id=$1',[vr.request.id])).status==='processing','Storage failure leaves processing, not a false completion');
 ok((await one('select is_active from users where id=$1',[vu.id])).is_active===false&&await one('select key from private_uploads where key=$1',[key]),'failed Storage cleanup preserves tracking and freezes access');
 ok((await call('/admin/users/'+vu.id,'PATCH',{is_active:true},at)).status===404,'processing account cannot be reactivated');
 ok((await call('/account-deletion/admin/'+vr.request.id,'PATCH',{status:'declined',public_message:'Do not reset processing.'},at)).status===409,'processing cannot be reset through review endpoint');
 failStorage=false;const retry=await call('/account-deletion/admin/'+vr.request.id+'/complete','POST',completion,at);
 assert.equal(retry.status,200,JSON.stringify(retry.data));ok(retry.data.request.status==='completed','failed deletion can be safely retried');
 ok(deleted.some(r=>r.url.endsWith('/vendor-documents')&&r.keys.includes(key))&&deleted.some(r=>r.url.endsWith('/listings')&&r.keys.includes(vu.id+'/item.jpg')),'actual Storage DELETE calls cover known CR and public listing images');
 ok(deleted.every(r=>r.keys.every(k=>k.startsWith(vu.id+'/')))&&await one('select key from private_uploads where key=$1',[otherKey]),'other users’ Storage keys are never deleted');
 const closed=await one('select * from vendors where id=$1',[v.id]);ok(closed.status==='suspended'&&closed.business_name==='Closed store'&&!closed.id_document_url&&!closed.bank_iban&&!closed.logo_url,'vendor profile and bank details removed');
 ok((await one('select images,status from listings where id=$1',[item.id])).images.length===0,'listings unpublished and file references removed');
 ok(await one('select id from orders where id=$1 and buyer_id=$2',[preserved.id,other.id]),'other customer’s order survives vendor deletion');
 ok(await one('select id from vendor_statements where id=$1',[statement.id]),'financial statement history is not cascade-deleted');
 await assert.rejects(()=>query("update vendors set status='verified' where id=$1",[v.id]));ok(true,'closed store cannot be republished');
 await assert.rejects(()=>query("update listings set status='active' where id=$1",[item.id]));ok(true,'closed listings cannot be republished');
 const cleaned=await one('select reason,internal_note from account_deletion_requests where id=$1',[vr.request.id]);ok(!cleaned.reason&&!cleaned.internal_note,'completion minimises request free-text');
 ok((await one("select count(*)::int n from audit_log where action='privacy.deletion_completed' and entity_id=$1",[vr.request.id])).n===1,'completion creates a minimal audit event');
 console.log(`\n${count} deletion integration checks passed (Storage HTTP stub; not live Supabase certification).`);
}catch(e){console.error(logs);throw e;}finally{if(child?.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}await new Promise(r=>storage.close(r));await pool.end();}
