// Integration suite: isolated PostgreSQL + actual compiled API + local Storage HTTP stub.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn,spawnSync} from 'node:child_process';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
const require=createRequire(new URL('../api/package.json',import.meta.url));
const root=new URL('../',import.meta.url).pathname;
const url=new URL(process.env.DATABASE_URL||'postgresql://invalid/invalid');
if(!['127.0.0.1','localhost','postgres'].includes(url.hostname)||!url.pathname.endsWith('_test'))throw Error('Only isolated *_test databases allowed');
if(process.env.NODE_ENV==='production')throw Error('Never test against production');
process.env.JWT_SECRET ||= 'integration-only-secret-at-least-32-characters';
process.env.PIN_PEPPER ||= 'integration-only-pepper-at-least-32-characters';
process.env.MFA_ENCRYPTION_KEY ||= 'ab'.repeat(32);
process.env.PGSSL='false';
const {pool,one,query}=require('../api/dist/db');
const {signToken}=require('../api/dist/auth');
const {signChallengeToken}=require('../api/dist/pin');
const {encryptSecret,recoveryHash}=require('../api/dist/mfa');
const bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),OTP=require('otpauth'),sharp=require('sharp');
let count=0,child,logs='',bucketPublic=false;const stored=new Map();
const ok=(v,m)=>{assert(v,m);console.log('PASS',m);count++;};
const storage=createServer(async(req,res)=>{
 const chunks=[];for await(const c of req)chunks.push(c);const body=Buffer.concat(chunks);
 res.setHeader('Content-Type','application/json');
 if(req.url.startsWith('/storage/v1/bucket/'))return res.end(JSON.stringify({public:bucketPublic}));
 if(req.url.startsWith('/storage/v1/object/sign/'))return res.end(JSON.stringify({signedURL:'/object/sign/private/test.jpg?token=stub'}));
 if(req.method==='POST'&&req.url.startsWith('/storage/v1/object/')){stored.set(req.url,{body,type:req.headers['content-type']});return res.end('{}');}
 res.statusCode=404;res.end('{}');
});
const base=`http://127.0.0.1:${process.env.TEST_PORT||4014}/api`;
async function call(path,method='GET',body,token){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),headers:r.headers};}
async function upload(token,contents,purpose='kyc',name='image.png',type='image/png'){
 const f=new FormData();f.append('files',new Blob([contents],{type}),name);
 const r=await fetch(base+'/uploads'+(purpose?'?purpose='+purpose:''),{method:'POST',headers:{Authorization:'Bearer '+token},body:f});return {status:r.status,data:await r.json()};
}
try {
 await query('delete from security_rate_limits'); // isolated test DB only; deterministic reruns
 await new Promise(r=>storage.listen(0,'127.0.0.1',r));
 const env={...process.env,PORT:process.env.TEST_PORT||'4014',EMAIL_PROVIDER:'none',CORS_ORIGINS:'https://trusted.example',SUPABASE_URL:'http://127.0.0.1:'+storage.address().port,SUPABASE_SERVICE_ROLE_KEY:'local-stub-only',SUPABASE_PRIVATE_BUCKET:'vendor-documents'};
 child=spawn(process.execPath,['dist/server.js'],{cwd:root+'api',env,stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('API startup timeout '+logs)),10000);child.stdout.on('data',d=>{logs+=d;if(logs.includes('listening on')){clearTimeout(t);resolve();}});child.stderr.on('data',d=>logs+=d);child.once('exit',c=>{clearTimeout(t);reject(Error('API exited '+c+' '+logs));});});
 const suffix=Date.now().toString();const password='Security-test-password!';const hash=await bcrypt.hash(password,10);
 async function user(role='buyer'){return one("insert into users(full_name,phone,email,password_hash,role) values('Security test',$1,$2,$3,$4) returning *",['974'+randomUUID().replace(/\D/g,'').slice(0,12),randomUUID()+'@example.invalid',hash,role]);}
 const buyer=await user(),vendorUser=await user('vendor'),other=await user('vendor'),admin=await user('admin');
 let token=await signToken(buyer.id,'buyer');const old=token;const pinStep=await signChallengeToken(buyer.id);
 ok((await call('/auth/me','GET',undefined,token)).status===200,'issued session is usable');
 await query('update users set sessions_valid_from=now() where id=$1',[buyer.id]);
 ok((await call('/auth/me','GET',undefined,old)).status===401,'cutoff revokes existing session');
 ok((await call('/auth/login/pin','POST',{pin_token:pinStep,pin:'7391'})).status===400,'revocation also invalidates PIN step token');
 const legacy=jwt.sign({sub:buyer.id,role:'buyer'},process.env.JWT_SECRET,{expiresIn:'1h'});
 ok((await call('/auth/me','GET',undefined,legacy)).status===401,'legacy untracked JWT is rejected');
 token=await signToken(buyer.id,'buyer');let second=await signToken(buyer.id,'buyer');
 const sessions=await call('/auth/sessions','GET',undefined,token);
 ok(sessions.data.sessions.length===2 && sessions.data.sessions.filter(s=>s.current).length===1,'session list identifies current session');
 await call('/auth/logout-others','POST',{},token);
 ok((await call('/auth/me','GET',undefined,second)).status===401 && (await call('/auth/me','GET',undefined,token)).status===200,'sign out other sessions preserves current');
 const changed=await call('/auth/change-password','POST',{current_password:password,new_password:'New-security-test-password!'},token);
 ok(changed.status===200 && !!changed.data.token,'password change returns replacement session');
 ok((await call('/auth/me','GET',undefined,token)).status===401,'password change revokes previous session');
 token=changed.data.token;
 await call('/auth/logout','POST',{},token);
 ok((await call('/auth/me','GET',undefined,token)).status===401,'logout revokes copied token');
 token=await signToken(buyer.id,'buyer');await query('update users set is_active=false where id=$1',[buyer.id]);await query('update users set is_active=true where id=$1',[buyer.id]);
 ok((await call('/auth/me','GET',undefined,token)).status===401,'disable then enable never revives old token');token=await signToken(buyer.id,'buyer');
 const noMfa=await call('/auth/login','POST',{identifier:admin.email,password});
 ok(noMfa.status===403 && !noMfa.data.token,'unenrolled admin cannot obtain password-only session');
 const secret=new OTP.Secret({size:20});const recovery='AB12CD34EF56AB12CD34EF56';
 await query('update users set mfa_secret=$2,mfa_recovery_hashes=$3 where id=$1',[admin.id,encryptSecret(secret.base32),JSON.stringify([recoveryHash(recovery)])]);
 const challenge=await call('/auth/login','POST',{identifier:admin.email,password});
 ok(challenge.data.mfa_required && !challenge.data.token,'admin password returns limited MFA challenge only');
 ok((await call('/auth/me','GET',undefined,challenge.data.mfa_token)).status===401,'MFA challenge is not a session');
 const totp=new OTP.TOTP({secret});const code=totp.generate();
 const auth=await call('/auth/login/mfa','POST',{mfa_token:challenge.data.mfa_token,code});
 ok(auth.status===200&&!!auth.data.token,'valid TOTP completes admin sign-in');
 ok((await call('/auth/login/mfa','POST',{mfa_token:challenge.data.mfa_token,code})).status===400,'TOTP replay blocked');
 ok((await call('/auth/login/mfa','POST',{mfa_token:challenge.data.mfa_token,code:recovery})).status===200,'one-use recovery code accepted');
 ok((await call('/auth/login/mfa','POST',{mfa_token:challenge.data.mfa_token,code:recovery})).status===400,'used recovery code rejected');
 const regBody={full_name:'Registered buyer',phone:'974'+Date.now().toString().slice(-8),email:randomUUID()+'@example.invalid',password,pin:'7391',role:'buyer'};
 const registration=await call('/auth/register','POST',regBody);
 ok(registration.status===201 && !!registration.data.token,'registration issues a persisted usable session');
 const login=await call('/auth/login','POST',{identifier:regBody.email,password});
 ok(login.data.pin_required && !login.data.token,'buyer password requires PIN step');
 const pinLogin=await call('/auth/login/pin','POST',{pin_token:login.data.pin_token,pin:regBody.pin});
 ok(pinLogin.status===200 && !!pinLogin.data.token,'correct PIN completes buyer login');
 const pinChange=await call('/auth/pin/change','POST',{current_pin:regBody.pin,new_pin:'6842'},pinLogin.data.token);
 ok(pinChange.status===200 && !!pinChange.data.token,'PIN change returns a replacement session');
 ok((await call('/auth/me','GET',undefined,pinLogin.data.token)).status===401,'PIN change revokes previous session');
 const reset=await call('/auth/admin/reset-pin','POST',{user_id:registration.data.user.id},auth.data.token);
 ok(reset.status===200 && reset.data.temp_pin.length===4,'MFA administrator can issue temporary PIN');
 ok((await call('/auth/me','GET',undefined,pinChange.data.token)).status===401,'admin PIN reset immediately revokes target sessions');
 const afterReset=await call('/auth/login','POST',{identifier:regBody.email,password});
 const temporary=await call('/auth/login/pin','POST',{pin_token:afterReset.data.pin_token,pin:reset.data.temp_pin});
 ok(temporary.data.pin_setup_required && !temporary.data.token,'temporary PIN cannot become a normal session');
 const setup=await call('/auth/pin/setup','POST',{setup_token:temporary.data.setup_token,pin:reset.data.temp_pin==='9573'?'8462':'9573'});
 ok(setup.status===200 && !!setup.data.token,'temporary PIN setup completes after choosing new PIN');
 ok((await call('/auth/pin/setup','POST',{setup_token:temporary.data.setup_token,pin:'7391'})).status===400,'used PIN setup token cannot be reused');
 const imp=await call('/admin/users/'+buyer.id+'/impersonate','POST',{},auth.data.token);
 ok(imp.status===200 && (await call('/auth/me','GET',undefined,imp.data.token)).status===200,'admin impersonation uses a tracked parent session');
 ok((await call('/auth/sessions','GET',undefined,imp.data.token)).status===403,'impersonation cannot manage target security');
 await call('/auth/logout','POST',{},auth.data.token);
 ok((await call('/auth/me','GET',undefined,imp.data.token)).status===401,'revoking admin parent also rejects impersonated session');
 // Restore a test admin session for document-ownership checks below.
 auth.data.token=await signToken(admin.id,'admin');
 const vt=await signToken(vendorUser.id,'vendor'),ot=await signToken(other.id,'vendor');
 const vendor=await one("insert into vendors(user_id,business_name,slug,whatsapp,country,city,status) values($1,'Secure Test Store',$2,'97455550001','Qatar','Doha','verified') returning *",[vendorUser.id,'security-'+suffix]);
 await one("insert into vendors(user_id,business_name,slug,whatsapp,country,city,status) values($1,'Other Test Store',$2,'97455550003','Qatar','Doha','verified') returning *",[other.id,'other-security-'+suffix]);
 const category=await one("insert into categories(name,slug,kind) values($1,$2,'product') returning *",['Security category '+suffix,'security-category-'+suffix]);
 const listing=await one("insert into listings(vendor_id,category_id,kind,title,slug,price,quantity,status,supplier_note) values($1,$2,'product','Security item','security-item',50,1,'active','PRIVATE SUPPLIER') returning *",[vendor.id,category.id]);
 const publicDetail=await call('/listings/'+listing.id);
 ok(publicDetail.status===200 && !('supplier_note' in publicDetail.data.listing),'public detail excludes supplier notes');
 const store=await call('/vendors/'+vendor.slug);
 ok(store.status===200 && !('supplier_note' in store.data.listings[0]),'storefront excludes supplier notes');
 const orderBody={items:[{listing_id:listing.id,qty:1}],contact_name:'Test Buyer',contact_phone:'97455550002',delivery_address:'Collection from store',city:'Doha',country:'Qatar',fulfilment_mode:'pickup'};
 const race=await Promise.all([call('/orders/checkout','POST',{...orderBody,request_id:randomUUID()}),call('/orders/checkout','POST',{...orderBody,request_id:randomUUID()})]);
 ok(race.filter(r=>r.status===201).length===1 && race.filter(r=>r.status===409).length===1,'concurrent last-unit checkout: only one succeeds');
 const order=race.find(r=>r.status===201).data.orders[0];
 ok((await call('/orders/vendor/'+order.id+'/status','PATCH',{status:'cancelled'},ot)).status===404,'other vendor cannot cancel order');
 const cancelled=await call('/orders/vendor/'+order.id+'/status','PATCH',{status:'cancelled'},vt);
 ok(cancelled.status===200 && (await one('select quantity from listings where id=$1',[listing.id])).quantity===1,'cancellation restores reserved stock');
 await call('/orders/vendor/'+order.id+'/status','PATCH',{status:'cancelled'},vt);
 ok((await one('select quantity from listings where id=$1',[listing.id])).quantity===1,'repeated cancellation never restores twice');
 ok((await call('/orders/vendor/'+order.id+'/status','PATCH',{status:'pending'},vt)).status===409,'cancelled order cannot reopen');
 const request_id=randomUUID();const duplicate=await Promise.all([call('/orders/checkout','POST',{...orderBody,request_id}),call('/orders/checkout','POST',{...orderBody,request_id})]);
 ok(duplicate.every(r=>r.status===201) && duplicate[0].data.orders[0].id===duplicate[1].data.orders[0].id,'concurrent retry replays same order');
 ok((await call('/orders/checkout','POST',{...orderBody,request_id,contact_name:'Changed buyer'})).status===409,'idempotency key cannot change payload');
 await query('update categories set is_banned=true where id=$1',[category.id]);
 ok((await call('/orders/quote','POST',{items:orderBody.items,fulfilment_mode:'pickup'})).status===400,'banned category cannot be quoted');
 ok((await call('/listings/'+listing.id)).status===404,'banned category cannot open directly');
 const complaint=await one("insert into complaints(code,subject,body,reporter_phone,reporter_id,admin_note) values($1,'Test complaint','Test complaint body','97455550002',$2,'PRIVATE ADMIN') returning *",['CMP-'+suffix,buyer.id]);
 ok((await call('/complaints/track/'+complaint.code)).status===400,'complaint code alone denied');
 ok((await call('/complaints/track/'+complaint.code+'?phone=97455550099')).status===404,'wrong complaint phone denied');
 const track=await call('/complaints/track/'+complaint.code+'?phone=97455550002');
 ok(track.status===200&&!('admin_note'in track.data.complaint),'complaint full-phone lookup redacts staff notes');
 ok((await call('/complaints/track/'+complaint.code,'GET',undefined,token)).status===200,'complaint owner can track while signed in');
 const serviceCategory=await one("select id from categories where kind='service' and not is_banned limit 1");
 const service=await one("insert into listings(vendor_id,category_id,kind,title,slug,price,duration_mins,status) values($1,$2,'service','History service','history-service',80,45,'active') returning *",[vendor.id,serviceCategory.id]);
 const bookingBody={listing_id:service.id,contact_name:'History buyer',contact_phone:'97455550123'};
 const ownedBooking=await call('/bookings','POST',bookingBody,token);
 ok(ownedBooking.status===201,'signed-in consumer can book using existing guest-compatible flow');
 await call('/bookings','POST',bookingBody);
 const history=await call('/bookings/mine','GET',undefined,token);
 ok(history.status===200 && history.data.bookings.length===1 && history.data.bookings[0].id===ownedBooking.data.booking.id && !('vendor_note' in history.data.bookings[0]),'booking history is ownership-scoped, redacted, and never claims matching-phone guest bookings');
 ok((await call('/bookings/mine')).status===401,'booking history requires authentication');
 const fake=await upload(vt,Buffer.from('not an image'),'','fake.jpg','image/jpeg');
 ok(fake.status===415,'spoofed image MIME does not bypass byte validation');
 const image=await sharp({create:{width:16,height:16,channels:3,background:'#ff0000'}}).png().toBuffer();
 const document=await upload(vt,image);
 ok(document.status===201 && document.data.urls[0].startsWith('kyc://'),'KYC upload returns private object reference, not public URL');
 const reference=document.data.urls[0];
 ok((await call('/uploads/document?key='+encodeURIComponent(reference),'GET',undefined,ot)).status===404,'other vendor cannot retrieve private document');
 ok((await call('/uploads/document?key='+encodeURIComponent(reference),'GET',undefined,vt)).status===200,'document owner receives expiring signed access');
 ok((await call('/uploads/document?key='+encodeURIComponent(reference),'GET',undefined,auth.data.token)).status===200,'authorised admin can review private document');
 ok((await call('/vendors/me','PATCH',{id_document_url:reference},ot)).status===403,'another vendor cannot attach someone else document');
 ok((await call('/vendors/me','PATCH',{id_document_url:'https://example.com/id.jpg'},vt)).status===422,'public KYC links rejected');
 ok((await call('/vendors/me','PATCH',{id_document_url:reference},vt)).status===200,'owner can attach private document');
 ok([...stored.values()].every(v=>v.type==='image/jpeg'&&v.body[0]===255&&v.body[1]===216),'stored images are decoded and re-encoded JPEGs');
 bucketPublic=true;
 ok((await upload(vt,image)).status===503,'misconfigured public KYC bucket fails closed');bucketPublic=false;
 const cors=await fetch(base+'/health',{headers:{Origin:'https://untrusted.netlify.app'}});
 ok(!cors.headers.get('access-control-allow-origin'),'untrusted Netlify origin is not whitelisted');
 const trusted=await fetch(base+'/health',{headers:{Origin:'https://trusted.example'}});
 ok(trusted.headers.get('access-control-allow-origin')==='https://trusted.example','exact configured origin accepted');
 const configCheck=spawnSync(process.execPath,['-e',"require('./dist/config')"],{cwd:root+'api',env:{...process.env,NODE_ENV:'production',JWT_SECRET:'',CORS_ORIGINS:'https://trusted.example'}});
 ok(configCheck.status!==0,'production refuses missing/weak JWT secret');
 const protectedTables=await query("select relname,relrowsecurity from pg_class where relnamespace='public'::regnamespace and relname in ('users','orders','private_uploads','auth_sessions')");
 ok(protectedTables.length===4 && protectedTables.every(t=>t.relrowsecurity),'sensitive tables have RLS enabled');
 console.log(`\n${count} security/commerce integration checks passed. Storage checks use a local stub, not production Supabase.`);
} catch(e){console.error(logs);throw e;} finally {
 if(child && child.exitCode===null){child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));}
 await new Promise(r=>storage.close(r));await pool.end();
}
