import {FormEvent,useEffect,useState} from 'react';
import {api} from '../../lib/api';
import {DeletionRequest,RequestStatus} from '../DeleteAccount';
import '../legal.css';
type AdminRequest=DeletionRequest&{user_id:string;full_name:string;role:string;reason?:string;internal_note?:string};
type Detail={request:AdminRequest;blockers:Record<string,number>;private_documents:number};
export default function AdminDeletion(){
 const [rows,setRows]=useState<AdminRequest[]>([]),[detail,setDetail]=useState<Detail|null>(null),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [status,setStatus]=useState('in_review'),[message,setMessage]=useState(''),[internal,setInternal]=useState(''),[retention,setRetention]=useState(''),[date,setDate]=useState(''),[confirmation,setConfirmation]=useState(''),[history,setHistory]=useState(false),[external,setExternal]=useState(false),[financial,setFinancial]=useState(false);
 async function load(){try{setRows((await api.get<{requests:AdminRequest[]}>(`/account-deletion/admin?offset=${offset}`)).requests);}catch(e:any){setError(e.message);}}
 useEffect(()=>{void load();},[offset]);
 async function select(id:string){setBusy(true);setError('');setDetail(null);setNotice('');try{const d=await api.get<Detail>(`/account-deletion/admin/${id}`);setDetail(d);setStatus('in_review');setMessage(d.request.public_message||'');setInternal(d.request.internal_note||'');setRetention(d.request.retention_summary||'');setDate(d.request.retention_review_date?.slice(0,10)||'');setHistory(false);setExternal(false);setFinancial(false);setConfirmation('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function review(e:FormEvent){e.preventDefault();if(!detail)return;setBusy(true);setError('');try{await api.patch(`/account-deletion/admin/${detail.request.id}`,{status,public_message:message,internal_note:internal});await select(detail.request.id);await load();setNotice('Review saved. The account has not been deleted.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function complete(e:FormEvent){e.preventDefault();if(!detail||!window.confirm('This closes account access and deletes profile details and known uploaded objects. Historical and external copies must already be reviewed. Continue?'))return;setBusy(true);setError('');try{await api.post(`/account-deletion/admin/${detail.request.id}/complete`,{confirmation,history_reviewed:history,external_copies_reviewed:external,financial_reviewed:financial,retention_summary:retention,retention_review_date:date,public_message:message});await select(detail.request.id);await load();setNotice('Reviewed profile/file deletion completed. Follow up retained records on the recorded review date.');}catch(e:any){setError(e.message);await load();}finally{setBusy(false);}}
 const active=detail&&['pending','in_review','needs_action','processing'].includes(detail.request.status);
 const blocked=detail&&Object.values(detail.blockers).some(n=>n>0);
 return <div className="privacy-admin" lang="en" dir="ltr"><header><h1>Privacy requests</h1><p>Review account-deletion requests and retained-record follow-ups. This is not a one-click purge of linked commercial records.</p></header>
 <div className="legal-warning"><strong>Manual review is essential.</strong><p>Before completing, minimise historical personal data and review retention reasons, outstanding liabilities, guest/unlinked records, external copies and legacy public documents. The action removes the active profile, credentials, known owned uploads and sessions; it preserves linked history and other customers’ records. See <code>docs/ACCOUNT-DELETION-RUNBOOK.md</code> in the repository.</p></div>
 {error&&<p className="privacy-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="privacy-actions"><button className="btn" disabled={busy} onClick={()=>void load()}>Refresh requests</button><button className="btn" disabled={busy||offset===0} onClick={()=>{setOffset(Math.max(0,offset-100));setDetail(null);}}>Previous 100</button><button className="btn" disabled={busy||rows.length<100} onClick={()=>{setOffset(offset+100);setDetail(null);}}>Next 100</button><span>Showing {rows.length?offset+1:0}–{offset+rows.length}</span></div>
 <p className="muted">No email notification or automatic retention purge. Check this queue and review dates regularly.</p>
 {!rows.length&&<p>No requests on this page.</p>}<div className="privacy-admin-list">{rows.map(r=><div className="privacy-card" key={r.id}><span className="privacy-state">{r.status.replace(/_/g,' ')}</span><p><strong>{r.full_name||'Removed account'}</strong> · {r.role||'—'}</p><p>{r.reference}</p>{r.retention_review_date&&<p>Retention review: <strong>{r.retention_review_date.slice(0,10)}</strong>{new Date(r.retention_review_date)<new Date()?' — due':''}</p>}<button className="btn btn-sm" disabled={busy} onClick={()=>void select(r.id)}>Review request</button></div>)}</div>
 {detail&&<section className="privacy-card"><h2>Request review</h2><RequestStatus r={detail.request}/><p><strong>Account ID:</strong> <code>{detail.request.user_id}</code></p>{detail.request.reason&&<p><strong>Customer’s reason:</strong> {detail.request.reason}</p>}<div className="privacy-meta">{Object.entries(detail.blockers).map(([k,n])=><div key={k}><strong>{n}</strong>{k.replace(/_/g,' ')}</div>)}<div><strong>{detail.private_documents}</strong>Tracked private documents</div></div><p>Counts are safeguards, not a substitute for reconciliation. Unlinked guest orders, unbilled fees, free-text and independent copies need manual investigation.</p>
 {active&&<><form className="privacy-form" onSubmit={review}><h3>Review response</h3><label htmlFor="privacy-message">Message visible to the requester<textarea id="privacy-message" required minLength={10} maxLength={1000} rows={3} value={message} onChange={e=>setMessage(e.target.value)}/></label><p>Do not include internal notes, third-party details or sensitive retained data. The receipt holder can read this response.</p>{detail.request.status!=='processing'&&<><label htmlFor="privacy-status">Review status<select id="privacy-status" value={status} onChange={e=>setStatus(e.target.value)}><option value="in_review">In review</option><option value="needs_action">Needs customer action</option><option value="declined">Declined — explain why</option></select></label><label htmlFor="privacy-internal">Internal note<textarea id="privacy-internal" maxLength={1500} rows={3} value={internal} onChange={e=>setInternal(e.target.value)}/></label><button className="btn" disabled={busy}>Save review only</button></>}</form>
 <form className="privacy-form" onSubmit={complete}><h3>Complete reviewed deletion</h3>{blocked&&<p className="privacy-error">Completion is blocked by outstanding records above. Resolve them and refresh before proceeding.</p>}<p>The account is blocked when processing starts. If Storage cleanup fails, the request stays processing and can be retried; it is not reported as completed. There is no online undo after processing starts.</p><label htmlFor="privacy-retention">Retained records, purpose/legal reason and exceptions<textarea id="privacy-retention" required minLength={20} maxLength={1500} rows={5} value={retention} onChange={e=>setRetention(e.target.value)} placeholder="Specify categories, why each remains, when or on what event it can be erased, backup/cache/third-party exceptions and the minimal closure record. Do not paste personal data."/></label><label htmlFor="privacy-date">Next manual retained-record review date<input id="privacy-date" type="date" required min={new Date(Date.now()+86400000).toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="privacy-check"><input type="checkbox" required checked={history} onChange={e=>setHistory(e.target.checked)}/><span>I reviewed historical account-linked and identifiable guest records, removed/anonymised unnecessary personal data, and documented the necessity and disposal plan for retained records without harming other parties.</span></label><label className="privacy-check"><input type="checkbox" required checked={external} onChange={e=>setExternal(e.target.checked)}/><span>I checked legacy/public/orphaned documents, externally hosted files, caches, backups and independent copies, completed required manual cleanup or documented lawful limitations, and understand that only known owned uploads are deleted automatically.</span></label><label className="privacy-check"><input type="checkbox" required checked={financial} onChange={e=>setFinancial(e.target.checked)}/><span>I reconciled outstanding financial obligations, including unbilled fees and unlinked transactions, and have authority to complete this request.</span></label><label htmlFor="privacy-confirmation">Type COMPLETE REVIEWED DELETION<input id="privacy-confirmation" required autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><p>The requester message entered above will be the final outcome. Explain what was removed and any remaining limits; do not claim all data has been erased.</p><button className="btn btn-danger" disabled={busy||!!blocked||!history||!external||!financial||confirmation!=='COMPLETE REVIEWED DELETION'||message.trim().length<10}>{busy?'Processing…':detail.request.status==='processing'?'Retry reviewed completion':'Complete reviewed deletion'}</button></form></>}
 {!active&&<p>This request is closed. Retention review and disposal must still be carried out manually using the recorded decision. Do not reactivate a deleted profile.</p>}</section>}
 </div>;
}
