import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  app: { flex: 1 }, page: { flex: 1 }, scroll: { paddingHorizontal: 18, paddingBottom: 25 },
  welcomeBg: { flex: 1 }, welcomeOverlay: { flex: 1, paddingHorizontal: 24 }, welcomeTop: { paddingTop: 22 }, welcomeSlide: { width: 345, flex: 1, justifyContent: 'center', alignItems: 'flex-start', paddingBottom: 8 }, welcomeIcon: { width: 76, height: 76, borderRadius: 23, alignItems: 'center', justifyContent: 'center', marginBottom: 24 }, welcomeTitle: { color: '#fff', fontSize: 34, lineHeight: 40, fontWeight: '900', letterSpacing: -.8, maxWidth: 330 }, welcomeText: { color: 'rgba(255,255,255,.86)', fontSize: 16, lineHeight: 24, marginTop: 15, maxWidth: 320 }, dots: { flexDirection: 'row', gap: 7, justifyContent: 'center', marginBottom: 22 }, dot: { width: 8, height: 8, borderRadius: 5 }, welcomeActions: { gap: 11, paddingBottom: 22 }, browseGuest: { color: '#fff', textAlign: 'center', fontWeight: '800', paddingVertical: 7, fontSize: 14 },
  homeHead: { height: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, homeHeadRight: { flexDirection: 'row', alignItems: 'center', gap: 11 }, hello: { fontSize: 13, fontWeight: '700', maxWidth: 92 }, signInLink: { fontSize: 14, fontWeight: '800' }, search: { height: 49, borderRadius: 14, borderWidth: 1, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 8 }, searchText: { fontSize: 14 }, heroCard: { marginTop: 15, borderRadius: 20, padding: 21, overflow: 'hidden' }, heroEyebrow: { color: '#D9DDF1', fontWeight: '800', fontSize: 10, letterSpacing: 1.2 }, heroTitle: { color: '#fff', fontSize: 25, lineHeight: 30, fontWeight: '900', marginTop: 7 }, heroCopy: { color: '#D9DDF1', fontSize: 13, lineHeight: 19, marginTop: 8, maxWidth: 278 }, heroCta: { flexDirection: 'row', gap: 8, alignSelf: 'flex-start', alignItems: 'center', paddingHorizontal: 13, height: 37, borderRadius: 11, marginTop: 17 }, heroCtaText: { color: '#161B36', fontWeight: '900', fontSize: 12 },
  sectionTitle: { marginTop: 22, marginBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sectionHeading: { fontSize: 18, fontWeight: '900', letterSpacing: -.3 }, seeAll: { fontSize: 13, fontWeight: '800' }, categoryRail: { gap: 10, paddingRight: 18 }, category: { width: 111, minHeight: 132, padding: 11, borderRadius: 16 }, categoryIcon: { width: 39, height: 39, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, categoryName: { fontSize: 13, fontWeight: '800', marginTop: 12 }, categoryKind: { fontSize: 10, marginTop: 2 }, listingRail: { gap: 11, paddingRight: 18 }, listingCard: { borderWidth: 1, borderRadius: 15, overflow: 'hidden', flexDirection: 'row', marginBottom: 10 }, listingCardCompact: { width: 172, flexDirection: 'column', marginBottom: 0 }, listingImage: { width: 107, height: 108, resizeMode: 'cover', alignItems: 'center', justifyContent: 'center' }, listingCardCompactImage: {}, listingInfo: { padding: 11, flex: 1, gap: 4 }, listingTitle: { fontSize: 14, lineHeight: 18, fontWeight: '800' }, listingVendor: { fontSize: 11, lineHeight: 15 }, servicePill: { alignSelf: 'flex-start', fontSize: 9, fontWeight: '900', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6 }, railEmpty: { height: 100, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  tabs: { zIndex: 30, borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-around', paddingTop: 7, paddingHorizontal: 4, elevation: 14, shadowColor: '#17291F', shadowOpacity: .1, shadowRadius: 10 }, tab: { flex: 1, alignItems: 'center', gap: 3 }, tabText: { fontSize: 9, fontWeight: '800' }, tabCenterIcon: { height: 38, width: 38, borderRadius: 20, marginTop: -18, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: '#fff' }, tabBadge: { position: 'absolute', minWidth: 15, height: 15, borderRadius: 8, alignItems: 'center', justifyContent: 'center', right: -10, top: -5 }, tabBadgeText: { fontSize: 8, fontWeight: '900', color: '#161B36' },
  browseSearch: { marginHorizontal: 16, height: 50, borderRadius: 13, flexDirection: 'row', alignItems: 'center', gap: 3 }, inlineField: { borderWidth: 0, backgroundColor: 'transparent', paddingHorizontal: 4, flex: 1, minHeight: 47 }, filterRail: { gap: 8, paddingHorizontal: 16, paddingVertical: 8 }, resultsLine: { flexDirection: 'row', justifyContent: 'space-between', marginHorizontal: 18, marginVertical: 7 }, resultText: { fontSize: 12 }, sortText: { fontSize: 12, fontWeight: '800' }, browseList: { paddingHorizontal: 17, paddingBottom: 90 }, sheetLabel: { fontSize: 13, fontWeight: '800', marginBottom: 7 }, radioRow: { flexDirection: 'row', alignItems: 'center', gap: 10, height: 42 }, radioText: { fontSize: 14 }, priceFields: { flexDirection: 'row', gap: 11 },
  authPage: { flex: 1 }, authScroll: { paddingHorizontal: 24, paddingTop: 19, paddingBottom: 45 }, authBack: { width: 38, height: 38, justifyContent: 'center', marginBottom: 20 }, authTitle: { fontSize: 30, lineHeight: 35, fontWeight: '900', letterSpacing: -.7, marginTop: 31 }, authSubtitle: { fontSize: 14, lineHeight: 20, marginTop: 8, marginBottom: 25 }, forgot: { fontSize: 13, fontWeight: '800', textAlign: 'right', paddingVertical: 6 }, authSwitch: { textAlign: 'center', fontSize: 13, marginTop: 6 }, webPortalLink: { textAlign: 'center', fontSize: 12, marginTop: 24, textDecorationLine: 'underline' }, terms: { fontSize: 11, textAlign: 'center', lineHeight: 16, marginTop: 14 }, pinField: { fontSize: 26, letterSpacing: 10, textAlign: 'center' }, recoveryTabs: { flexDirection: 'row', gap: 8, marginBottom: 19 },
  detailScroll: { paddingBottom: 97 }, detailImage: { width: 390, height: 290, resizeMode: 'cover', alignItems: 'center', justifyContent: 'center' }, detailBody: { paddingHorizontal: 18, paddingTop: 17 }, kindLine: { flexDirection: 'row', alignItems: 'center', gap: 9 }, kindTag: { fontSize: 10, fontWeight: '900', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 7, overflow: 'hidden' }, duration: { fontSize: 12 }, detailTitle: { fontSize: 25, lineHeight: 30, fontWeight: '900', letterSpacing: -.4, marginTop: 8 }, detailDescription: { fontSize: 14, lineHeight: 21, marginTop: 14 }, vendorRow: { flexDirection: 'row', alignItems: 'center', gap: 11 }, vendorAvatar: { height: 45, width: 45, borderRadius: 12, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, vendorLogo: { width: '100%', height: '100%', resizeMode: 'cover' }, vendorName: { fontSize: 14, fontWeight: '800' }, vendorMeta: { fontSize: 12, lineHeight: 17 }, reviewStars: { fontSize: 15 }, reviewTitle: { fontWeight: '800', fontSize: 13, marginTop: 5 }, reviewCopy: { fontSize: 13, lineHeight: 18, marginTop: 4 }, reviewDate: { fontSize: 10, marginTop: 8 }, noReview: { fontSize: 13, marginBottom: 10 }, buyBar: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 12, borderTopWidth: 1 },
  storeHero: { height: 142, justifyContent: 'center', alignItems: 'center' }, storeLogo: { height: 92, width: 92, borderRadius: 22, resizeMode: 'cover' }, storeInfo: { paddingHorizontal: 18, paddingBottom: 28 }, storeMeta: { flexDirection: 'row', alignItems: 'center', gap: 5, marginVertical: 16 },
  cartList: { padding: 16, gap: 10, paddingBottom: 88 }, cartItem: { flexDirection: 'row', gap: 11 }, cartImage: { width: 80, height: 80, borderRadius: 10, resizeMode: 'cover', alignItems: 'center', justifyContent: 'center' }, qtyRow: { flexDirection: 'row', alignItems: 'center', gap: 11, marginTop: 6 }, qtyButton: { width: 26, height: 26, borderWidth: 1, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, qty: { minWidth: 15, textAlign: 'center', fontWeight: '800' }, cartFooter: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 12, borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, totalLabel: { fontSize: 12, fontWeight: '700' },
  checkoutScroll: { padding: 18, paddingBottom: 42 }, checkoutHeading: { fontSize: 17, fontWeight: '900', marginTop: 23, marginBottom: 12 }, checkoutModes: { flexDirection: 'row', gap: 9, marginBottom: 10 }, paymentOption: { minHeight: 48, borderRadius: 12, borderWidth: 1, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 9 }, paymentText: { fontSize: 14, fontWeight: '700' }, quoteCard: { marginTop: 9 }, quoteTitle: { fontSize: 15, fontWeight: '900', marginBottom: 5 }, quoteVendor: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 5 }, quoteTotal: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  ordersList: { padding: 17, paddingBottom: 30, gap: 10 }, orderCard: { padding: 14 }, orderTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 }, orderCode: { fontSize: 14, fontWeight: '900' }, orderDate: { fontSize: 11, marginTop: 3 }, status: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8 }, orderBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, trackLink: { fontSize: 13, fontWeight: '900' },
  trackScroll: { padding: 18, gap: 2 }, trackProduct: { fontSize: 15, fontWeight: '800' }, trackDetail: { fontSize: 13, marginTop: 4 },
  accountScroll: { padding: 17, paddingBottom: 93 }, profileHero: { minHeight: 108, borderRadius: 18, padding: 17, flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 14 }, profileAvatar: { width: 55, height: 55, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, profileInitial: { fontSize: 23, fontWeight: '900', color: '#161B36' }, profileName: { color: '#fff', fontSize: 18, fontWeight: '900' }, profileContact: { color: '#D9DDF1', fontSize: 12, marginTop: 3 }, accountRow: { minHeight: 67, flexDirection: 'row', alignItems: 'center', gap: 12 }, accountIcon: { height: 40, width: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, accountTitle: { fontSize: 14, fontWeight: '800' }, accountSubtitle: { fontSize: 11, marginTop: 3 }, accountFootnote: { fontSize: 11, lineHeight: 15, textAlign: 'center', marginTop: 19 },
  supportScroll: { padding: 18, gap: 4 }, supportHero: { borderRadius: 18, alignItems: 'center', padding: 22, marginBottom: 9 }, supportTitle: { fontSize: 21, fontWeight: '900', marginTop: 10 }, supportCopy: { textAlign: 'center', fontSize: 13, lineHeight: 19, marginTop: 6 }, webPortalText: { fontSize: 12, textAlign: 'center', paddingHorizontal: 33 },

  /* Reference-led emerald / citrus marketplace styling */
  marketScroll: { paddingBottom: 24 }, marketTopbar: { minHeight: 66, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 8 }, marketLocation: { flex: 1, minWidth: 0, height: 36, borderRadius: 18, paddingHorizontal: 8, flexDirection: 'row', gap: 2, alignItems: 'center' }, marketLocationText: { fontSize: 12, fontWeight: '800', flexShrink: 1 }, marketTopIcons: { flexDirection: 'row', gap: 7 },
  marketHero: { marginHorizontal: 13, borderRadius: 0, padding: 17, paddingTop: 15, overflow: 'hidden' }, marketHeroBadge: { height: 21, borderRadius: 11, backgroundColor: '#BDF8D1', alignSelf: 'flex-start', paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 4 }, marketHeroBadgeText: { fontSize: 8, fontWeight: '900', letterSpacing: .4 }, marketHeroTitle: { color: '#fff', fontSize: 25, lineHeight: 28, fontWeight: '900', marginTop: 9, letterSpacing: -.5 }, marketHeroCopy: { color: '#D9F5E5', fontSize: 12, lineHeight: 18, marginTop: 6, maxWidth: 330 }, marketSearchBox: { marginTop: 15, height: 48, borderRadius: 12, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 13 }, marketSearchCopy: { fontSize: 12, flex: 1 }, marketHeroFilters: { flexDirection: 'row', gap: 7, marginTop: 7 }, marketFilter: { flex: 1, height: 36, backgroundColor: '#fff', borderRadius: 8, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 4 }, marketFilterText: { fontSize: 11, fontWeight: '800' }, marketSearchButton: { marginTop: 8, height: 39, borderRadius: 20, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }, marketSearchButtonText: { color: '#fff', fontWeight: '900', fontSize: 13 },
  quickRail: { gap: 7, paddingHorizontal: 14, paddingTop: 10, paddingBottom: 2 }, quickChip: { paddingHorizontal: 10, height: 27, borderRadius: 14, justifyContent: 'center' }, quickChipText: { fontSize: 10, fontWeight: '700' }, trustGrid: { margin: 14, gap: 7, flexDirection: 'row', flexWrap: 'wrap' }, trustTile: { width: '48.8%', borderRadius: 8, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 7, shadowColor: '#122016', shadowOpacity: .03, shadowRadius: 4, elevation: 1 }, trustIcon: { height: 30, width: 30, borderRadius: 7, alignItems: 'center', justifyContent: 'center' }, trustTitle: { fontSize: 10, fontWeight: '900' }, trustSub: { fontSize: 9, marginTop: 2 }, stallRail: { gap: 9, paddingLeft: 14, paddingRight: 14 }, stallCard: { width: 116, minHeight: 116, borderRadius: 12, padding: 10 }, stallIcon: { width: 34, height: 34, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, stallTitle: { fontSize: 11, lineHeight: 14, fontWeight: '900', marginTop: 13 }, stallSub: { fontSize: 9, marginTop: 3 }, sectionCaption: { fontSize: 10, marginHorizontal: 18, marginBottom: 2 }, marketGrid: { paddingHorizontal: 14, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginTop: 10 }, sellBanner: { marginHorizontal: 14, marginTop: 23, borderRadius: 12, minHeight: 114, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, sellBannerEyebrow: { color: '#D6F7E3', fontSize: 8, fontWeight: '900', letterSpacing: .6 }, sellBannerTitle: { color: '#fff', fontSize: 17, lineHeight: 20, fontWeight: '900', marginTop: 4 }, sellBannerCopy: { color: '#D7F6E3', fontSize: 10, lineHeight: 14, marginTop: 4 }, sellBannerAction: { backgroundColor: '#fff', borderRadius: 22, height: 38, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 4 }, sellBannerActionText: { fontSize: 11, fontWeight: '900' },
  listingVisual: { position: 'relative' }, listingImageCompact: { width: '100%', height: 135 }, favouriteButton: { position: 'absolute', right: 7, top: 7, height: 28, width: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, itemRibbon: { position: 'absolute', left: 0, bottom: 0, paddingHorizontal: 6, paddingVertical: 3, borderTopRightRadius: 7 }, itemRibbonText: { color: '#fff', fontSize: 7, fontWeight: '900' }, ratingLine: { flexDirection: 'row', alignItems: 'center', gap: 3 }, ratingText: { fontSize: 9, fontWeight: '700' }, itemAction: { minHeight: 27, borderRadius: 7, marginTop: 3, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4 }, itemActionText: { fontSize: 9, fontWeight: '900' },
  referenceAuthScroll: { paddingBottom: 32 }, referenceTopbar: { minHeight: 63, paddingHorizontal: 17, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomColor: '#EAEAF0', borderBottomWidth: StyleSheet.hairlineWidth }, referenceBack: { height: 40, width: 30, justifyContent: 'center', alignItems: 'flex-start' }, currencyBadge: { borderRadius: 18, paddingHorizontal: 10, paddingVertical: 5, marginLeft: 'auto' }, currencyBadgeText: { fontSize: 9, fontWeight: '900', lineHeight: 12, textAlign: 'center' }, referenceBrandBlock: { alignItems: 'center', paddingHorizontal: 30, paddingTop: 22 }, referenceLogoCircle: { width: 94, height: 94, borderRadius: 47, alignItems: 'center', justifyContent: 'center', position: 'relative' }, referenceLogo: { width: 69, height: 69, resizeMode: 'contain' }, globeDot: { height: 27, width: 27, borderRadius: 14, position: 'absolute', right: -3, bottom: 2, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#fff' }, referenceWelcome: { fontSize: 29, fontWeight: '900', letterSpacing: -.8, marginTop: 19 }, referenceLanguage: { fontSize: 15, fontWeight: '900', marginTop: 4 }, referenceIntro: { fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 12, maxWidth: 310 }, referenceLoginCard: { marginHorizontal: 17, marginTop: 27, borderRadius: 16, borderWidth: 1, padding: 16, shadowColor: '#17291F', shadowOpacity: .05, shadowRadius: 12, elevation: 2 }, loginModeToggle: { height: 47, borderRadius: 24, padding: 4, flexDirection: 'row', marginBottom: 19 }, loginMode: { flex: 1, borderRadius: 21, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 }, loginModeText: { fontSize: 13, fontWeight: '900' }, fieldHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, referenceFieldLabel: { fontSize: 12, fontWeight: '900', marginBottom: 7 }, networkLabel: { fontSize: 10, fontWeight: '800', marginBottom: 7 }, referenceInputRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' }, countryCode: { height: 50, borderRadius: 10, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5 }, qatarFlag: { fontSize: 18 }, countryCodeText: { fontSize: 15, fontWeight: '900' }, referenceField: { minHeight: 50, borderRadius: 10, backgroundColor: '#F1F3FF', borderColor: 'transparent', fontSize: 15 }, referenceSignIn: { marginTop: 13, borderRadius: 25, minHeight: 55 }, orLine: { flexDirection: 'row', alignItems: 'center', gap: 8, marginVertical: 18 }, orStroke: { height: 1, flex: 1 }, orText: { fontSize: 9, fontWeight: '900', letterSpacing: 1 }, guestAccess: { borderRadius: 22, minHeight: 47 },
  pinReferencePage: { flex: 1 }, pinReferenceScroll: { paddingHorizontal: 25, paddingTop: 10, paddingBottom: 10 }, pinShield: { height: 84, width: 84, borderRadius: 42, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', position: 'relative' }, pinBolt: { position: 'absolute', right: -4, bottom: 2, height: 27, width: 27, borderRadius: 14, justifyContent: 'center', alignItems: 'center' }, pinReferenceTitle: { textAlign: 'center', fontSize: 24, fontWeight: '900', marginTop: 15, letterSpacing: -.7 }, pinReferenceIntro: { textAlign: 'center', fontSize: 15, lineHeight: 23, marginTop: 11 }, pinBoxes: { flexDirection: 'row', justifyContent: 'center', gap: 10, marginTop: 15 }, pinBox: { height: 55, width: 55, borderRadius: 14, borderWidth: 1, justifyContent: 'center', alignItems: 'center', shadowColor: '#13261A', shadowOpacity: .04, shadowRadius: 4 }, pinDigit: { fontSize: 33, fontWeight: '900' }, biometricStrip: { alignSelf: 'center', marginTop: 18, borderRadius: 18, minHeight: 35, paddingHorizontal: 16, alignItems: 'center', flexDirection: 'row', gap: 7 }, biometricText: { fontSize: 13, fontWeight: '900' }, forgotPinLink: { fontSize: 13, fontWeight: '900', textAlign: 'center', marginVertical: 12 }, pinVerifyButton: { marginTop: 18, borderRadius: 25, minHeight: 53 }, pinKeypad: { flexDirection: 'row', flexWrap: 'wrap', gap: 11, justifyContent: 'space-between', marginTop: 15 }, pinKey: { width: '30.5%', height: 50, borderRadius: 15, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, pinKeyText: { fontSize: 25, fontWeight: '800' }, pinSecurityNote: { fontSize: 11, textAlign: 'center', lineHeight: 16, marginTop: 22 },
  cartTopbar: { minHeight: 62, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 7 }, cartLocation: { marginLeft: 'auto', height: 31, paddingHorizontal: 8, borderRadius: 15, backgroundColor: '#FFF7EE', flexDirection: 'row', alignItems: 'center', gap: 4 }, cartLocationText: { fontSize: 9, fontWeight: '800' }, referenceCartScroll: { padding: 15, paddingBottom: 16 }, cartTitleRow: { marginBottom: 10 }, referenceCartTitle: { fontSize: 23, fontWeight: '900' }, cartCountPill: { fontSize: 11, paddingHorizontal: 7, paddingVertical: 4, borderRadius: 9 }, dispatchProgress: { borderRadius: 12, padding: 12, flexDirection: 'row', gap: 9, marginBottom: 13 }, dispatchIcon: { height: 34, width: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, dispatchHead: { flexDirection: 'row', justifyContent: 'space-between', gap: 5 }, dispatchTitle: { fontSize: 10, fontWeight: '900' }, progressTrack: { height: 5, borderRadius: 4, marginTop: 6, overflow: 'hidden' }, progressFill: { height: '100%', borderRadius: 4 }, dispatchCopy: { fontSize: 9, lineHeight: 13, marginTop: 6 }, vendorCartBlock: { borderWidth: 1, borderRadius: 13, padding: 11, marginBottom: 11 }, vendorCartHeading: { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: 9 }, vendorCartName: { fontSize: 11, fontWeight: '900', flex: 1 }, vendorCartChip: { paddingHorizontal: 7, paddingVertical: 3, borderRadius: 7 }, vendorCartChipText: { fontSize: 8, fontWeight: '800' }, referenceCartItem: { flexDirection: 'row', gap: 9, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#ECEDF2', paddingTop: 10, marginTop: 8 }, referenceCartImage: { height: 76, width: 76, borderRadius: 9, resizeMode: 'cover', alignItems: 'center', justifyContent: 'center' }, referenceCartItemTitle: { fontSize: 13, lineHeight: 16, fontWeight: '900' }, cartBadges: { flexDirection: 'row', gap: 5, alignItems: 'center', marginVertical: 5 }, cartFreshBadge: { paddingHorizontal: 5, paddingVertical: 2, borderRadius: 5, overflow: 'hidden', fontSize: 8, fontWeight: '900' }, importText: { fontSize: 8 }, cartItemControls: { justifyContent: 'space-between', alignItems: 'flex-end' }, roundQty: { height: 27, width: 27, borderRadius: 14, borderWidth: 1, justifyContent: 'center', alignItems: 'center' }, referenceCartFooter: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopWidth: 1, paddingHorizontal: 15, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, referenceCheckoutButton: { minWidth: 191, borderRadius: 23, minHeight: 46 },
  specialistTopbar: { minHeight: 61, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 7, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E8EAF2' }, specialistTopTitle: { fontSize: 16, fontWeight: '900' }, specialistTopSub: { fontSize: 9, fontWeight: '700' }, qatarMini: { borderRadius: 12, paddingHorizontal: 9, paddingVertical: 5 }, qatarMiniText: { fontSize: 9, fontWeight: '900' }, specialistScroll: { padding: 16, paddingBottom: 90 }, specialistProfile: { flexDirection: 'row', gap: 10, alignItems: 'center' }, specialistAvatar: { width: 68, height: 68, borderRadius: 10, resizeMode: 'cover', justifyContent: 'center', alignItems: 'center' }, specialistName: { fontSize: 15, fontWeight: '900', lineHeight: 18 }, specialistInfo: { fontSize: 10, marginTop: 3 }, serviceTagRail: { flexDirection: 'row', gap: 6, marginTop: 12 }, serviceMetaTag: { height: 28, borderRadius: 14, paddingHorizontal: 9, flexDirection: 'row', gap: 4, alignItems: 'center' }, serviceMetaText: { fontSize: 9, fontWeight: '800' }, bookingSectionTitle: { fontSize: 16, fontWeight: '900', marginTop: 22, marginBottom: 9 }, selectedService: { minHeight: 78, borderRadius: 11, borderWidth: 1, padding: 11, flexDirection: 'row', gap: 9, alignItems: 'center' }, serviceRadio: { height: 19, width: 19, borderRadius: 10, borderWidth: 2, alignItems: 'center', justifyContent: 'center' }, serviceRadioDot: { width: 9, height: 9, borderRadius: 5 }, serviceChoiceTitle: { fontSize: 13, fontWeight: '900', lineHeight: 16 }, serviceChoiceSub: { fontSize: 10, lineHeight: 14, marginTop: 3 }, locationToggle: { height: 47, padding: 4, borderRadius: 9, flexDirection: 'row', gap: 3 }, locationOption: { flex: 1, borderRadius: 7, flexDirection: 'row', gap: 5, alignItems: 'center', justifyContent: 'center' }, locationOptionText: { fontSize: 11, fontWeight: '900' }, dateSuggestions: { flexDirection: 'row', gap: 8, marginBottom: 11 }, dateSuggestion: { flex: 1, minHeight: 39, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, dateSuggestionText: { fontSize: 10, fontWeight: '800' }, estimateCard: { padding: 13, borderRadius: 12, marginTop: 5 }, estimateLabel: { fontSize: 9, fontWeight: '900', letterSpacing: .4 }, estimateLine: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 9, gap: 10 }, estimateTotal: { fontSize: 16, fontWeight: '900' }, escrowNotice: { borderRadius: 8, padding: 9, marginTop: 11, flexDirection: 'row', gap: 7, alignItems: 'center' }, escrowNoticeText: { flex: 1, fontSize: 9, lineHeight: 13 }, bookingFooter: { position: 'absolute', bottom: 0, left: 0, right: 0, paddingHorizontal: 14, paddingVertical: 9, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, bookNowButton: { minWidth: 155, borderRadius: 22, minHeight: 45 },

  /* Whole-app colourful marketplace continuation */
  accountGuestHeader: { minHeight: 62, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center' }, accountClose: { height: 38, width: 38, borderRadius: 19, marginLeft: 'auto', alignItems: 'center', justifyContent: 'center' }, accountGuestScroll: { padding: 17, paddingBottom: 24 }, guestHero: { borderRadius: 20, padding: 22, alignItems: 'center' }, guestAvatar: { height: 68, width: 68, borderRadius: 34, alignItems: 'center', justifyContent: 'center' }, guestHeroTitle: { fontSize: 22, fontWeight: '900', marginTop: 13 }, guestHeroCopy: { fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 8 }, guestSignButton: { marginTop: 18, width: '100%', borderRadius: 24 }, guestCreateButton: { marginTop: 9, width: '100%', borderRadius: 24 }, profileTop: { minHeight: 174, padding: 17, paddingTop: 13 }, profileTopRow: { flexDirection: 'row', alignItems: 'center' }, profileBell: { height: 37, width: 37, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginLeft: 'auto', backgroundColor: 'rgba(255,255,255,.16)' }, profileIdentity: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 18 }, profileVerified: { alignSelf: 'flex-start', marginTop: 6, backgroundColor: 'rgba(255,255,255,.18)', borderRadius: 10, paddingHorizontal: 7, paddingVertical: 3, flexDirection: 'row', gap: 4, alignItems: 'center' }, profileVerifiedText: { color: '#fff', fontSize: 9, fontWeight: '900' }, colourAccountScroll: { padding: 16, paddingBottom: 24 }, accountQuickGrid: { flexDirection: 'row', gap: 7, marginTop: -41, marginBottom: 21 }, quickAccount: { flex: 1, minHeight: 77, borderRadius: 11, alignItems: 'center', justifyContent: 'center', gap: 5, shadowColor: '#173222', shadowOpacity: .08, shadowRadius: 7, elevation: 3 }, quickAccountIcon: { width: 30, height: 30, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, quickAccountText: { fontSize: 10, fontWeight: '900' }, accountSectionLabel: { fontSize: 10, fontWeight: '900', letterSpacing: .7, marginTop: 13, marginBottom: 7 }, accountGroup: { borderWidth: 1, paddingHorizontal: 12, borderRadius: 14 }, colourSignOut: { marginTop: 20, borderRadius: 13 },
  browseReferenceHeader: { minHeight: 49, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' }, browseBell: { marginLeft: 'auto', height: 35, width: 35, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, browseLocationRow: { marginHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 3, marginBottom: 8 }, browseLocationText: { fontSize: 16, fontWeight: '900' }, browseSearchBox: { height: 48, marginHorizontal: 13, borderRadius: 9, paddingLeft: 11, paddingRight: 5, flexDirection: 'row', alignItems: 'center', gap: 5 }, browseReferenceField: { borderWidth: 0, backgroundColor: 'transparent', minHeight: 46, flex: 1, paddingHorizontal: 3, fontSize: 11 }, browseFilterIcon: { height: 38, width: 38, borderRadius: 7, alignItems: 'center', justifyContent: 'center' }, sourceLine: { minHeight: 38, marginHorizontal: 13, marginTop: 8, borderRadius: 8, paddingHorizontal: 9, flexDirection: 'row', gap: 5, alignItems: 'center' }, sourceText: { fontSize: 10, flex: 1 }, sourceChange: { fontSize: 10, fontWeight: '900' }, browseFilterRail: { paddingHorizontal: 13, paddingTop: 9, gap: 7 }, categoryFilterBox: { minHeight: 57, marginHorizontal: 13, marginTop: 11, borderRadius: 9, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' }, categoryFilterItem: { flex: 1, alignItems: 'center', gap: 3, paddingHorizontal: 3 }, categoryFilterText: { fontSize: 8, fontWeight: '800', maxWidth: 70 }, browseHeadline: { marginTop: 13, paddingHorizontal: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, browseHeading: { fontSize: 18, fontWeight: '900' }, browseSubheading: { fontSize: 10, marginTop: 2 }, gridToggle: { height: 34, width: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, browseReferenceList: { paddingBottom: 90 }, browseColumn: { justifyContent: 'space-between', paddingHorizontal: 13, marginTop: 10 },
  detailTopbar: { minHeight: 58, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 8 }, detailCircle: { height: 38, width: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', shadowColor: '#163126', shadowOpacity: .07, shadowRadius: 5, elevation: 2 }, referenceDetailScroll: { paddingBottom: 16 }, referenceDetailImage: { width: 390, height: 290, resizeMode: 'cover', alignItems: 'center', justifyContent: 'center' }, detailReferenceBody: { padding: 16 }, detailTagRow: { flexDirection: 'row', alignItems: 'center', gap: 9 }, detailReferenceTag: { fontSize: 9, fontWeight: '900', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 7, overflow: 'hidden' }, detailStock: { fontSize: 10, fontWeight: '800' }, referenceDetailTitle: { fontSize: 24, lineHeight: 29, fontWeight: '900', marginTop: 11, letterSpacing: -.4 }, detailPriceLine: { flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 9 }, detailUnit: { fontSize: 11 }, sellerDetailCard: { marginTop: 17, padding: 11, borderRadius: 12 }, sellerDetailRow: { flexDirection: 'row', alignItems: 'center', gap: 9 }, sellerAvatar: { height: 45, width: 45, borderRadius: 12, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, sellerDetailName: { fontSize: 13, fontWeight: '900' }, sellerDetailMeta: { fontSize: 10, marginTop: 3 }, detailSectionTitle: { fontSize: 17, fontWeight: '900', marginTop: 22, marginBottom: 8 }, referenceDetailDescription: { fontSize: 13, lineHeight: 20 }, detailFacts: { marginTop: 16, flexDirection: 'row', justifyContent: 'space-between' }, detailFact: { alignItems: 'center', width: '31%', gap: 5 }, detailFactText: { fontSize: 9, textAlign: 'center', lineHeight: 12, fontWeight: '700' }, reviewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, writeReview: { marginTop: 18, fontSize: 11, fontWeight: '900' }, referenceReview: { borderRadius: 10, padding: 11, marginBottom: 8, shadowColor: '#173222', shadowOpacity: .03, shadowRadius: 4 }, detailPurchaseBar: { position: 'absolute', bottom: 0, left: 0, right: 0, minHeight: 72, borderTopWidth: 1, paddingHorizontal: 14, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, detailBuyButton: { minWidth: 177, minHeight: 47, borderRadius: 24 },

});

export const nx = StyleSheet.create({
  fixedTop: { minHeight: 62, paddingHorizontal: 14, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, zIndex: 5 },
  cityTrigger: { flex: 1, minWidth: 0, height: 38, borderRadius: 19, paddingHorizontal: 9, flexDirection: 'row', gap: 4, alignItems: 'center', justifyContent: 'center' },
  heroInput: { flex: 1, fontSize: 13, paddingVertical: 0, height: 46 },
  stall: { width: 84, borderRadius: 14, borderWidth: 1, paddingVertical: 9, paddingHorizontal: 6, alignItems: 'center' },
  stallImage: { width: 48, height: 48, borderRadius: 24 },
  stallTitle: { fontSize: 10, lineHeight: 13, fontWeight: '800', textAlign: 'center', marginTop: 7, minHeight: 26 },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  priceRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4, gap: 4 },
  cartCircle: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  bookPill: { height: 32, borderRadius: 16, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 4 },
  bookPillText: { color: '#fff', fontSize: 11, fontWeight: '900' },
  toastWrap: { position: 'absolute', left: 14, right: 14, alignItems: 'center', zIndex: 50 },
  toast: { backgroundColor: '#12251B', borderRadius: 14, paddingHorizontal: 14, minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 9, elevation: 16, shadowColor: '#000', shadowOpacity: .25, shadowRadius: 10 },
  toastText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  toastLink: { color: '#FFAA58', fontSize: 13, fontWeight: '900', marginLeft: 6 },
  phoneField: { height: 50, borderRadius: 12, borderWidth: 1, flexDirection: 'row', alignItems: 'center', marginBottom: 15, overflow: 'hidden' },
  phonePrefix: { paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 6 },
  phoneDivider: { width: 1, height: 26 },
  phoneInput: { flex: 1, height: 50, paddingHorizontal: 12, fontSize: 15, paddingVertical: 0 },
  profileHeader: { paddingHorizontal: 17, paddingTop: 12, paddingBottom: 20 },
  logoChip: { backgroundColor: '#fff', borderRadius: 14, paddingHorizontal: 10, paddingVertical: 6 },
  identity: { flexDirection: 'row', alignItems: 'center', gap: 13, marginTop: 18 },
  avatar: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontSize: 24, fontWeight: '900', color: '#05663F' },
  accountBody: { padding: 16, paddingBottom: 24 },
  tileGrid: { flexDirection: 'row', gap: 8 },
  tile: { flex: 1, minHeight: 92, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 8 },
  countPill: { minWidth: 24, height: 20, borderRadius: 10, paddingHorizontal: 7, alignItems: 'center', justifyContent: 'center' },
  countText: { fontSize: 11, fontWeight: '900' },
  countSpacer: { height: 20 },
});

export const ex = StyleSheet.create({
  browseTop: { paddingHorizontal: 13, paddingTop: 6, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 8 }, browseBack: { width: 34, height: 44, justifyContent: 'center' },
  searchBox: { flex: 1, height: 46, borderRadius: 12, borderWidth: 1, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }, searchInput: { flex: 1, fontSize: 14, paddingVertical: 0, height: 44 },
  filterButton: { width: 46, height: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, filterBadge: { position: 'absolute', top: -4, right: -4, minWidth: 17, height: 17, borderRadius: 9, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 }, filterBadgeText: { fontSize: 9, fontWeight: '900', color: '#1C1B17' },
  chipScroller: { flexGrow: 0 }, chipRail: { paddingHorizontal: 13, paddingVertical: 8, gap: 7, alignItems: 'center' }, chipDivider: { width: 1, height: 20 },
  resultsLine: { paddingHorizontal: 15, paddingBottom: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, resultsText: { fontSize: 12, flexShrink: 1 }, sortText: { fontSize: 12, fontWeight: '800' },
  gridContent: { paddingBottom: 16, flexGrow: 1 }, gridRow: { justifyContent: 'space-between', paddingHorizontal: 13, marginTop: 10 },
  cityWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 14 }, sheetActions: { flexDirection: 'row', gap: 10, marginTop: 8 },
  noteCard: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 13 }, noteIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, noteTitle: { fontSize: 14, fontWeight: '800' }, noteText: { fontSize: 12, marginTop: 3 }, noteAgo: { fontSize: 10 },
});

