import {FormEvent,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../lib/api';
import {useAuth} from '../state/AuthContext';
import {HelpPage} from './Legal';
export type DeletionRequest={id:string;reference:string;status:string;created_at:string;updated_at:string;public_message?:string;retention_summary?:string;retention_review_date?:string;completed_at?:string};
export function RequestStatus({r}:{r:DeletionRequest}){return <div className="privacy-card"><h3>{r.reference}</h3><span className="privacy-state">{r.status.replace(/_/g,' ')}</span><p>Submitted {new Date(r.created_at).toLocaleDateString('en-GB')} · Updated {new Date(r.updated_at).toLocaleDateString('en-GB')}</p>{r.public_message&&<p>{r.public_message}</p>}{r.retention_summary&&<p><strong>Retained records / exceptions:</strong> {r.retention_summary}</p>}{r.retention_review_date&&<p><strong>Manual retention review due:</strong> {r.retention_review_date.slice(0,10)}</p>}</div>;}
export default function DeleteAccount(){
 const {user,impersonating}=useAuth();
 const [requests,setRequests]=useState<DeletionRequest[]>([]),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[ack,setAck]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const [receipt,setReceipt]=useState<{reference:string;access_token:string}|null>(null),[reference,setReference]=useState(''),[token,setToken]=useState(''),[tracked,setTracked]=useState<DeletionRequest|null>(null);
 const eligible=!!user&&user.role!=='admin'&&!impersonating;
 async function load(){try{const r=await api.get<{requests:DeletionRequest[]}>('/account-deletion/requests');setRequests(r.requests);setLoaded(true);}catch(e:any){setError(e.message);}}
 useEffect(()=>{setLoaded(false);setRequests([]);if(eligible)void load();},[user?.id,eligible]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api.post<{request:DeletionRequest;access_token:string}>('/account-deletion/requests',{password,reason,acknowledge:ack});setRequests(old=>[r.request,...old]);const saved={reference:r.request.reference,access_token:r.access_token};setReceipt(saved);setReference(saved.reference);setToken(saved.access_token);setAck(false);setReason('');}catch(e:any){setError(e.message);}finally{setPassword('');setBusy(false);}}
 async function withdraw(r:DeletionRequest){if(!window.confirm('Withdraw this deletion request? Your account will remain open.'))return;setBusy(true);setError('');try{await api.post(`/account-deletion/requests/${r.id}/withdraw`);await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function track(e:FormEvent){e.preventDefault();setBusy(true);setError('');setTracked(null);try{const r=await api.post<{request:DeletionRequest}>('/account-deletion/status',{reference:reference.trim(),access_token:token.trim()});setTracked(r.request);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function download(){if(!receipt)return;const text=`Sokoni Hub — private account-deletion receipt\n\nReference: ${receipt.reference}\nAccess key: ${receipt.access_token}\n\nTrack at ${window.location.origin}/delete-account\n\nKeep this private. Anyone with both values can read the request status and retention outcome.\nThis is a request receipt, not proof of completed erasure.\nSupport: WhatsApp +974 6604 6431 or the existing Support page.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='sokoni-deletion-receipt.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const active=requests.some(r=>['pending','in_review','needs_action','processing'].includes(r.status));
 return <HelpPage title="Account deletion" subtitle="Request a reviewed account closure and keep track of the outcome.">
 <section><h2>What happens after you request deletion?</h2><ol><li>Sign in and confirm your current password. Save the private receipt.</li><li>An administrator reviews open orders, appointments, complaints and financial obligations. You may be asked to resolve outstanding matters.</li><li>Reviewed completion closes access and removes the active profile and known account-owned uploads. Necessary transaction, financial, dispute or security records may remain with an explained retention decision and review date.</li></ol><p>This is not instant erasure. Logging out, disabling an account, or submitting this form alone does not delete stored information. Historical free-text, backups, cached/public copies and copies held by vendors or other services need separate review. See the <Link to="/privacy">draft Privacy Policy</Link>.</p><p>You can withdraw before processing begins. Once processing starts, access may end and online withdrawal is no longer available. Your receipt lets you check progress without signing in. No automated email confirmation is sent.</p></section>
 {error&&<p className="privacy-error" role="alert">{error}</p>}
 {receipt&&<section aria-live="polite"><h2>Request received — save your receipt now</h2><p>The access key is shown only for this submission. It is not saved automatically in browser storage. Download it before leaving this page; it remains usable after your account closes.</p><pre className="privacy-receipt">Reference: {receipt.reference}{'\n'}Access key: {receipt.access_token}</pre><button className="btn btn-primary" onClick={download}>Download private receipt</button></section>}
 <section><h2>Submit a request</h2>{!user?<><p><Link className="btn btn-primary" to="/login?next=%2Fdelete-account">Sign in to request deletion</Link></p><p>Cannot sign in? Contact <Link to="/support">Support</Link> or WhatsApp +974 6604 6431 for a verified manual request. Do not send your password or PIN.</p></>:!eligible?<p>Requests must be made from your own buyer or vendor account, not through administrator impersonation. Administrator accounts require a separate controlled handover through Support.</p>:!loaded?<p>Loading your requests… <button className="btn btn-sm" disabled={busy} onClick={()=>void load()}>Retry</button></p>:active?<p>You already have an open request. Review its status below or contact Support with your reference.</p>:<form className="privacy-form" onSubmit={submit}><label htmlFor="deletion-password">Current account password<input id="deletion-password" type="password" autoComplete="current-password" required maxLength={200} value={password} onChange={e=>setPassword(e.target.value)}/></label><label htmlFor="deletion-reason">Reason (optional)<textarea id="deletion-reason" maxLength={500} rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Do not include passwords, PINs or sensitive documents."/></label><label className="privacy-check"><input type="checkbox" required checked={ack} onChange={e=>setAck(e.target.checked)}/><span>I am requesting deletion of my own account. I understand that review is required, access ends during processing, and necessary records may be retained with an explanation.</span></label><button className="btn btn-primary" disabled={busy||!ack}>{busy?'Submitting…':'Submit deletion request'}</button></form>}</section>
 {eligible&&requests.length>0&&<section><h2>Your requests</h2><button className="btn btn-sm" disabled={busy} onClick={()=>void load()}>Refresh status</button>{requests.map(r=><div key={r.id}><RequestStatus r={r}/>{['pending','in_review','needs_action'].includes(r.status)&&<button className="btn btn-sm" disabled={busy} onClick={()=>void withdraw(r)}>Withdraw request</button>}</div>)}</section>}
 <section><h2>Track using your receipt</h2><p>No login is required. Keep both values private and paste them exactly as saved.</p><form className="privacy-form" onSubmit={track}><label htmlFor="deletion-reference">Request reference<input id="deletion-reference" required maxLength={50} autoComplete="off" spellCheck={false} value={reference} onChange={e=>setReference(e.target.value)}/></label><label htmlFor="deletion-key">Private access key<input id="deletion-key" type="password" required minLength={64} maxLength={64} autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><button className="btn" disabled={busy}>{busy?'Checking…':'Check request status'}</button></form><div aria-live="polite">{tracked&&<RequestStatus r={tracked}/>}</div></section>
 </HelpPage>;
}
